const port = process.env.port || 5000;
const express = require('express');
const app = express();
const routes = require('./routers');
const initConfig = require('./config/initConfig');
const connectDatabase = require('./config/connectDatabase');
connectDatabase();
initConfig(app);
routes(app);
app.listen(port, ()=> console.log(`Listening on port ${port}...`));